### ISSUE TITLE
Are you still able to run the tool ?

### ISSUE THREAD

**Issue by Icare2000** [anothertobi/viseca-exporter#22]
Hi, i tried to run it today.... i cannot makeit?

2024/01/02 16:43:17 error listing all transactions: api call failed with status: 401 Unauthorized

Or did vieseca closed it completley

**Comment by anothertobi** [comment]
The old method where you extract the session cookie from the browser (https://github.com/anothertobi/viseca-exporter?tab=readme-ov-file#auth-w-browser) still works for me, but the new one that handles the whole auth flow is broken.

**Comment by Icare2000** [comment]
Now i made it work. i updated the doc a very little bit

**Comment by anothertobi** [comment]
Resolved with #23
