### ISSUE TITLE
Does it still work ? I get error when trying to acess api

### ISSUE THREAD

**Issue by Icare2000** [anothertobi/viseca-exporter#6]
api.one.viseca.ch/v1/transactions?stateType=unknown&offset=0&pagesize=20&dateTo=2023-04-10T2xxxxxxxxxxxxx:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by anothertobi** [comment]
The tool still works for me. But it seems like you're directly accessing the API and not using the tool. Is that correct?

If so, then you probably have something wrong with your URL. It should be similar to `https://api.one.viseca.ch/v1/card/0000000AAAAA0000/transactions?stateType=unknown&offset=0&pagesize=20` (of course your card ID `0000000AAAAA0000` will be different).

**Comment by Icare2000** [comment]
Hello, it works well, i can use your tools now instead of my old method.

i needed to adapt a bit the calling for Windows.... env variable are not possible ?

Thanks

**Comment by anothertobi** [comment]
Sorry, I don't use Windows myself and don't know what the best way to handle the env vars would be.

If you have some simple steps to add to the README, please open a PR :)
